prepare_data.py:
  tiling:
    csv: ./tiles
    srs: "EPSG:2056"
    split: 3
  label:
    shapefile: nw_thm_labels.shp
  output_folder: ../output

generate_training_sets.py:
  debug_mode: False
  datasets:
    aoi_tiles_geojson: ../output/tiles.geojson
    ground_truth_labels_geojson: ../output/labels.geojson
    orthophotos_web_service:
      type: WMS # supported values: 1. MIL = Map Image Layer 2. WMS
      url: https://wms.geo.admin.ch/service
      layers: ch.swisstopo.swissimage
      srs: "EPSG:2056"
  output_folder: ../output
  tile_size: 256 # per side, in pixels
  overwrite: False
  n_jobs: 10
  COCO_metadata:
    year: 2021
    version: 1.0
    description: Swiss Image Hinterground w/ Thermal panel detection
    contributor: swisstopo
    url: https://swisstopo.ch
    license:
      name: Unknown
      url:
    category:
        name: "Thermal Panel"
        supercategory: "Infrastructure"
        
make_predictions.py:
    working_folder: ../output
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
    detectron2_config_file: 'detectron2_config_TPNL_NE.yaml' # path relative to the working_folder
    model_weights:
        model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"
        pth_file: './logs/model_final.pth'
    do_train: True
  
assess_predictions.py:
  datasets:
    ground_truth_labels_geojson: ../output/ground_truth_labels.geojson
    image_metadata_json: ../output/img_metadata.json
    split_aoi_tiles_geojson: ../output/split_aoi_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: ../output/trn_predictions_at_0dot05_threshold.pkl
      val: ../output/val_predictions_at_0dot05_threshold.pkl
      tst: ../output/tst_predictions_at_0dot05_threshold.pkl
  output_folder: ../output
