common:
    debug: True
    working: &working_folder ./output
    class: 'Energy'
    category: 'Thermal panels'

prepare.py:
    dataset: /media/user/head_loop1/loop_405e-5f-dc22/405e-5f-dc22_hades/hades_atlas/atlas_set/set_thermal-panel
    conformation: conformation-26-256-aargau
    split_seed: 1
    split_prop: [ 0.7, 0.15, 0.15 ]

train_model.py:
    working_folder: ../output
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
    detectron2_config_file: 'detectron2_config_tpnl.yaml' # path relative to the working_folder
    model_weights:
        model_zoo_checkpoint_url: "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml"

make_predictions.py:
    working_folder: ../output
    log_subfolder: logs
    sample_tagged_img_subfolder: sample_tagged_images
    COCO_files: # relative paths, w/ respect to the working_folder
        trn: COCO_trn.json
        val: COCO_val.json
        tst: COCO_tst.json
        oth: COCO_oth.json
    detectron2_config_file: 'detectron2_config_tpnl.yaml' # path relative to the working_folder
    model_weights:
        pth_file: './logs/model_final.pth'
  
assess_predictions.py:
  datasets:
    ground_truth_labels_geojson: ../output/labels.geojson
    image_metadata_json: ../output/img_metadata.json
    split_aoi_tiles_geojson: ../output/split_aoi_tiles.geojson # aoi = Area of Interest
    predictions:
      trn: ../output/trn_predictions_at_0dot05_threshold.pkl
      val: ../output/val_predictions_at_0dot05_threshold.pkl
      tst: ../output/tst_predictions_at_0dot05_threshold.pkl
      oth: ../output/oth_predictions_at_0dot05_threshold.pkl
  output_folder: ../output

